Windows build workflow update attempt 1!

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -50,23 +50,19 @@ jobs:
 
           outputs=(
             "libcfallsave.so"
+            "cfallsave.dev.out"
             "cfallsave.test.out"
             "libcfallsave++.so"
+            "cfallsave++.dev.out"
             "cfallsave++.test.out"
           )
 
           for arch in "${archs[@]}"; do
-            if [ ! -d "$arch" ]; then
-              echo "$arch build for Linux failed!"
+            for output in "${outputs[@]}"; do
+              if [ ! -f "$arch/$output" ]; then
+                echo "$output build for Linux failed!"
 
-              exit 1
-            else
-              for output in "${outputs[@]}"; do
-                if [ ! -f "$arch/$output" ]; then
-                  echo "$output build for Linux failed!"
-
-                  exit 1
-                fi
-              done
-            fi
+                exit 1
+              fi
+            done
           done
diff --git a/.github/workflows/build-macos.yml b/.github/workflows/build-macos.yml
--- a/.github/workflows/build-macos.yml
+++ b/.github/workflows/build-macos.yml
@@ -48,23 +48,19 @@ jobs:
 
           outputs=(
             "libcfallsave.dylib"
+            "cfallsave.dev.out"
             "cfallsave.test.out"
             "libcfallsave++.dylib"
+            "cfallsave++.dev.out"
             "cfallsave++.test.out"
           )
 
           for arch in "${archs[@]}"; do
-            if [ ! -d "$arch" ]; then
-              echo "$arch build for macOS failed!"
+            for output in "${outputs[@]}"; do
+              if [ ! -f "$arch/$output" ]; then
+                echo "$output build for macOS failed!"
 
-              exit 1
-            else
-              for output in "${outputs[@]}"; do
-                if [ ! -f "$arch/$output" ]; then
-                  echo "$output build for macOS failed!"
-
-                  exit 1
-                fi
-              done
-            fi
+                exit 1
+              fi
+            done
           done
